export const FRUITS = [
  "Abiu",
  "Acai Berry",
  "Acerola",
  "African Apricot",
  "African Breadfruit",
  "African Cherry Orange",
  "African Cucumber",
  "African Eggplant",
  "African Horned Cucumber",
  "African Mango",
  "African Medlar",
  "African Moringa",
  "African Oil Palm",
  "African Pear",
  "African Plum",
  "African Star Apple",
  "African Walnut",
  "Agave Plant",
  "Ahuacatl",
  "Air Potato",
  "Akee Apple",
  "Alaska Wild Blueberry",
  "Albertine Orange",
  "Alemow",
  "Alligator Apple",
  "Alpine Strawberry",
  "Amazon Grape",
  "Amazonian Tree Grape",
  "Ambarella",
  "Ambrosial Apple",
  "American Black Elderberry",
  "American Blackberry",
  "American Chestnut",
  "American Cranberry",
  "American Elder",
  "American Grape",
  "American Hazelnut",
  "American Mayapple",
  "American Mulberry",
  "American Persimmon",
  "American Plum",
  "American Purple Grape",
  "American Red Raspberry",
  "American Serviceberry",
  "American Wild Plum",
  "Amla",
  "Angel's Trumpet",
  "Angola Pear",
  "Annona",
  "Antarctic Beech",
  "Apple",
  "Apple Berry",
  "Apple Cucumber",
  "Apple Guava",
  "Apple Mint",
  "Apple Rose",
  "Appleberry",
  "Applecactus",
  "Applesauce Plant",
  "Apricot",
  "Aprium",
  "Arabian Coffee",
  "Aratiles",
  "Arctic Beauty Kiwi",
  "Arctic Blackberry",
  "Arctic Bramble",
  "Arctic Cranberry",
  "Arctic Raspberry",
  "Arizona Elderberry",
  "Arizona Grape",
  "Arizona Walnut",
  "Armenian Blackberry",
  "Armenian Plum",
  "Aronia Berry",
  "Asian Cantaloupe",
  "Asian Pear",
  "Asian Persimmon",
  "Asian Plum",
  "Asian Raspberry",
  "Assyrian Plum",
  "Atlantic Hazelnut",
  "Atlas Berry",
  "Australian Apple Berry",
  "Australian Brush Cherry",
  "Australian Desert Lime",
  "Australian Finger Lime",
  "Australian Native Apple",
  "Australian Native Cherry",
  "Australian Native Plum",
  "Australian Red Cedar",
  "Australian Wild Lime",
  "Austrian Pine Nut",
  "Autumn Olive",
  "Autumn Royal Grape",
  "Avocado",
  "Azarole",
];
